[ubuntu_servers]
192.168.122.12 ansible_user=s1 ansible_ssh_private_key_file=/home/teifu142/ATE/UIT/NT542/NT542
192.168.122.5 ansible_user=s2 ansible_ssh_private_key_file=/home/teifu142/ATE/UIT/NT542/NT542
