; [ubuntu_servers:vars]
; ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=300s -o ServerAliveInterval=60 -o ServerAliveCountMax=5'

[ubuntu_servers]
192.168.122.216 ansible_user=s1 ansible_ssh_private_key_file=/home/teifu142/ATE/UIT/NT542/NT542
; 192.168.122.5 ansible_user=s2 ansible_ssh_private_key_file=/home/teifu142/ATE/UIT/NT542/NT542
