---
- name: "Phase 4: SSH Hardening"
  hosts: ubuntu_servers
  become: yes
  tags: phase4
  vars:
    playbook_name: "phase_4"

  vars_files:
    - ../group_vars/all.yml

  roles:
    - phase_4/ssh
    - common/fetch_results
