[localhost]
localhost ansible_connection=local

[kvm_vms]
u22 ansible_host=localhost
u24 ansible_host=localhost

[localhost]
localhost ansible_connection=local

[kvm_vms][localhost]
localhost ansible_connection=local

[kvm_vms]
u22 ansible_host=localhost
u24 ansible_host=localhost
u22 ansible_host=localhost
u24 ansible_host=localhost