---
# Handlers for Phase 2 Services

- name: restart postfix
  listen: "restart postfix"
  service:
    name: postfix
    state: restarted

- name: restart exim4
  listen: "restart exim4"
  service:
    name: exim4
    state: restarted
